In [1]:
import json
import requests
import pandas as pd
import numpy as np

In [2]:
headers = {
        'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36'
}
response = requests.get(url="https://projects.fivethirtyeight.com/soccer-predictions/forecasts/2020_premier-league_forecast.json",headers=headers)

In [3]:
data = response.json()["forecasts"]

In [4]:
df = pd.read_csv("../data/premier_FiveThirtyEight.csv")
df

   team_code                team_name  end_season_rank  end_season_points
0        SOU              Southampton               15                 43
1        MAN        Manchester United                2                 74
2        BHA   Brighton & Hove Albion               16                 41
3        WOL  Wolverhampton Wanderers               13                 45
4        TOT        Tottenham Hotspur                7                 62
5        AVL              Aston Villa               11                 55
6        LEE             Leeds United                9                 59
7        WHU          West Ham United                6                 65
8        MNC          Manchester City                1                 86
9        ARS                  Arsenal                8                 61
10       CRY           Crystal Palace               14                 44
11       WBA     West Bromwich Albion               19                 26
12       FUL                   Fulham               18                 28
13      SHEF         Sheffield United               20                 23
14       LIV                Liverpool                3                 69
15       NEW         Newcastle United               12                 45
16       EVE                  Everton               10                 59
17       BRN                  Burnley               17                 39
18       CHE                  Chelsea                4                 67
19       LEI           Leicester City                5                 66

In [5]:
df_point = df.copy()
df_performace_by_week = df.copy()

In [6]:
for i in range(35,-1,-1):
    SPIs = []
    current_points = []
    for team in range(20):
        temp_data = data[i]["teams"][team]
        global_rating = temp_data['global_rating']
        point = temp_data['current_points']
        SPIs.append(global_rating)
        current_points.append(point)
    df[f'SPI_{35-i}'] = SPIs
    df_point[f'point_{35-i}'] = current_points

In [7]:
df

,team_code,team_name,end_season_rank,end_season_points,SPI_0,SPI_1,SPI_2,SPI_3,SPI_4,SPI_5,...,SPI_26,SPI_27,SPI_28,SPI_29,SPI_30,SPI_31,SPI_32,SPI_33,SPI_34,SPI_35
0,SOU,Southampton,15,43,72.47932,72.31624,70.94386,71.65689,72.31242,72.98865,...,70.09618,70.25452,67.88548,67.99760,67.99760,66.98538,66.80914,67.07499,67.00995,67.00995
1,MAN,Manchester United,2,74,86.83190,86.83190,85.37987,83.96362,81.34273,82.69237,...,87.83323,87.70445,88.48703,88.13239,88.72573,89.08216,87.19872,85.69021,85.52917,85.52917
2,BHA,Brighton & Hove Albion,16,41,68.02657,68.45778,70.26278,71.44657,70.38213,71.53225,...,77.96108,78.01265,78.28780,79.09613,79.03140,80.12606,79.09685,79.66174,78.71135,78.71135
3,WOL,Wolverhampton Wanderers,13,45,78.00348,78.53875,78.45722,76.14209,75.80769,75.59703,...,73.01224,73.28708,73.15549,73.19403,69.87157,69.87985,70.85036,69.50278,69.60656,69.60656
4,TOT,Tottenham Hotspur,7,62,78.50745,77.90705,78.56143,78.86683,81.30301,80.64401,...,80.80936,78.64824,77.93990,76.88934,76.88934,77.86326,76.59145,76.85306,78.05972,78.05972
5,AVL,Aston Villa,11,55,66.48339,66.48339,67.60605,69.03522,72.42795,73.94631,...,73.41278,73.82455,73.78506,74.08914,73.88651,74.54807,73.70673,72.73110,72.17909,72.17909
6,LEE,Leeds United,9,59,64.08564,64.26965,63.58782,64.25541,65.87499,66.40524,...,71.46154,71.55889,72.04875,73.22801,72.88293,71.71315,72.90044,74.72841,74.93956,74.93956
7,WHU,West Ham United,6,65,70.38160,68.77400,69.01171,71.37968,73.65363,74.09911,...,77.44613,76.56452,76.13809,75.42943,74.31547,74.88327,74.28949,75.89111,75.99829,75.99829
8,MNC,Manchester City,1,86,94.11285,94.11285,94.15617,92.84689,92.01631,92.00107,...,93.71233,93.67251,93.67373,93.61926,93.52492,93.26143,93.19323,92.38613,92.78275,92.42451
9,ARS,Arsenal,8,61,77.16360,79.16636,78.82578,78.68867,78.55612,78.85240,...,83.13410,81.41168,82.33211,83.47866,83.04305,83.90236,82.97759,82.71256,83.71535,83.71535
10,CRY,Crystal Palace,14,44,67.69013,68.03427,69.70830,68.75453,67.67626,66.65791,...,60.87131,60.48507,58.66877,58.66877,58.83176,59.09297,61.13147,61.90367,61.54908,61.54908
11,WBA,West Bromwich Albion,19,26,61.66534,60.24432,58.23659,58.44440,58.34010,58.62065,...,57.06836,59.41799,61.34147,61.34147,59.78433,59.77537,60.99652,60.12471,59.72011,59.72011
12,FUL,Fulham,18,28,64.17512,61.95933,61.80004,59.94378,60.70167,61.47324,...,70.82157,70.07271,70.38070,70.02451,70.02451,69.99564,68.63801,68.70725,68.01165,68.01165
13,SHEF,Sheffield United,20,23,69.20166,68.42515,67.58978,66.93202,67.38923,66.53809,...,58.30329,58.13256,56.88823,57.29125,57.39857,56.04961,54.06139,55.73144,56.30491,56.30491
14,LIV,Liverpool,3,69,91.06966,90.62100,91.38289,91.43829,88.80550,88.68522,...,87.84108,88.85169,89.17450,88.34954,88.10693,88.10693,88.09373,88.84424,89.17243,89.17243
15,NEW,Newcastle United,12,45,64.72499,66.46392,64.78206,64.22024,65.21804,64.29025,...,62.22831,63.88879,63.81584,64.19613,64.47032,63.34588,64.74216,66.79243,67.79495,67.79495
16,EVE,Everton,10,59,74.04602,74.95779,75.80106,76.60437,76.89088,76.76819,...,71.52313,71.62039,71.73210,72.52695,73.44877,72.61383,73.45842,73.32021,72.27832,72.27832
17,BRN,Burnley,17,39,69.08173,69.08173,69.22054,69.04738,67.74821,68.18174,...,67.57380,66.53917,66.06311,65.78060,69.00230,68.13623,69.09659,66.86460,66.79333,66.79333
18,CHE,Chelsea,4,67,85.37204,85.03603,84.16062,83.65035,84.51701,83.54506,...,89.35318,87.42701,87.33253,87.10019,88.41768,89.41157,89.90936,89.92075,89.99834,90.53043
19,LEI,Leicester City,5,66,79.02248,80.34309,79.59120,81.70637,79.83031,78.73250,...,79.28745,78.50632,78.75406,78.75406,79.62694,80.47512,79.90236,79.69660,78.22239,78.22239

In [8]:
for i in range(34,-1,-1):
    week_wins = []
    week_points = []
    week_games = []
    for team in range(20):
        this_week_data = data[i]["teams"][team]
        last_week_data = data[i+1]["teams"][team]
        this_week_point = this_week_data['current_points']-last_week_data['current_points']
        this_week_win = this_week_data['current_wins']-last_week_data['current_wins']
        this_week_game = this_week_data['current_wins']-last_week_data['current_wins']+this_week_data['current_ties']-last_week_data['current_ties']+this_week_data['current_losses']-last_week_data['current_losses']
        week_wins.append(this_week_win)
        week_points.append(this_week_point)
        week_games.append(this_week_game)
    df_performace_by_week[f'week_wins_{35-i}'] = week_wins
    df_performace_by_week[f'week_points_{35-i}'] = week_points
    df_performace_by_week[f'week_games_{35-i}'] = week_games

In [10]:
df.to_csv('../data/premier/premier_SPI.csv',index = False)
df_point.to_csv('../data/premier/premier_points_by_week.csv',index = False)
df_performace_by_week.to_csv('../data/premier/premier_performance_by_week.csv',index = False)

In [20]:
df_SPI_by_month = df[['team_code','team_name','end_season_rank','end_season_points','SPI_0','SPI_4','SPI_7','SPI_10','SPI_14','SPI_19',
                      'SPI_23','SPI_27','SPI_31','SPI_35']]
df_SPI_by_month=df_SPI_by_month.rename(columns={"SPI_4": "SPI_1", "SPI_7": "SPI_2", "SPI_10": "SPI_3", "SPI_14": "SPI_4", "SPI_19": "SPI_5", "SPI_23": "SPI_6",
                              "SPI_27": "SPI_7", "SPI_31": "SPI_8", "SPI_35": "SPI_9"})

df_SPI_by_month

,team_code,team_name,end_season_rank,end_season_points,SPI_0,SPI_1,SPI_2,SPI_3,SPI_4,SPI_5,SPI_6,SPI_7,SPI_8,SPI_9
0,SOU,Southampton,15,43,72.47932,72.31242,73.42171,72.99666,75.26409,70.00285,68.39797,70.25452,66.98538,67.00995
1,MAN,Manchester United,2,74,86.83190,81.34273,83.18712,84.20368,84.50883,87.31463,86.88586,87.70445,89.08216,85.52917
2,BHA,Brighton & Hove Albion,16,41,68.02657,70.38213,71.04280,73.59825,73.00412,77.18579,77.28393,78.01265,80.12606,78.71135
3,WOL,Wolverhampton Wanderers,13,45,78.00348,75.80769,76.12677,76.83793,75.19875,72.65890,71.90533,73.28708,69.87985,69.60656
4,TOT,Tottenham Hotspur,7,62,78.50745,81.30301,80.49740,83.96441,81.19827,78.79943,79.23503,78.64824,77.86326,78.05972
5,AVL,Aston Villa,11,55,66.48339,72.42795,71.42075,73.85515,78.65968,76.18240,75.53811,73.82455,74.54807,72.17909
6,LEE,Leeds United,9,59,64.08564,65.87499,67.47882,69.06605,68.81474,68.43408,71.20411,71.55889,71.71315,74.93956
7,WHU,West Ham United,6,65,70.38160,73.65363,74.36361,74.21062,74.45101,76.60244,77.65946,76.56452,74.88327,75.99829
8,MNC,Manchester City,1,86,94.11285,92.01631,92.97156,93.90327,93.30009,93.47974,93.72844,93.67251,93.26143,92.42451
9,ARS,Arsenal,8,61,77.16360,78.55612,80.66272,77.99236,79.59102,80.67475,82.44178,81.41168,83.90236,83.71535
10,CRY,Crystal Palace,14,44,67.69013,67.67626,66.27512,66.16244,65.24378,65.71741,62.07877,60.48507,59.09297,61.54908
11,WBA,West Bromwich Albion,19,26,61.66534,58.34010,58.99400,57.66053,53.26460,52.30263,55.20247,59.41799,59.77537,59.72011
12,FUL,Fulham,18,28,64.17512,60.70167,61.36065,63.42956,66.12919,64.56377,70.40265,70.07271,69.99564,68.01165
13,SHEF,Sheffield United,20,23,69.20166,67.38923,67.39074,65.57787,62.80547,64.70032,63.09723,58.13256,56.04961,56.30491
14,LIV,Liverpool,3,69,91.06966,88.80550,88.64414,87.72162,88.07168,89.42383,88.54297,88.85169,88.10693,89.17243
15,NEW,Newcastle United,12,45,64.72499,65.21804,65.52203,65.83824,63.53393,63.12945,63.02354,63.88879,63.34588,67.79495
16,EVE,Everton,10,59,74.04602,76.89088,75.23714,72.51078,75.19609,72.76464,73.23885,71.62039,72.61383,72.27832
17,BRN,Burnley,17,39,69.08173,67.74821,67.29205,65.96897,67.46507,66.33861,67.42203,66.53917,68.13623,66.79333
18,CHE,Chelsea,4,67,85.37204,84.51701,85.59760,87.55405,86.79399,85.98116,88.06528,87.42701,89.41157,90.53043
19,LEI,Leicester City,5,66,79.02248,79.83031,79.91916,77.83384,78.85620,80.14604,76.38605,78.50632,80.47512,78.22239

In [21]:
df_SPI_by_month.to_csv('../data/premier/premier_points_by_month.csv',index = False)

In [5]:
df_performance_by_month = df.copy()
month_index = [0,4,7,10,14,19,23,27,31,35]
for i in range(1,len(month_index)):
    month_win_percentage = []
    month_point_percentage = []
    actual_index = 35-month_index[i]
    last_index = 35-month_index[i-1]
    for team in range(20):
        this_month = data[actual_index]["teams"][team]
        last_month = data[last_index]["teams"][team]
        game = this_month['current_wins']-last_month['current_wins']+this_month['current_ties']-last_month['current_ties']+this_month['current_losses']-last_month['current_losses']
        win_percentage = (this_month['current_wins']-last_month['current_wins'])/game
        point_percentage = (this_month['current_points']-last_month['current_points'])/game
        month_win_percentage.append(win_percentage)
        month_point_percentage.append(point_percentage)
    df_performance_by_month[f'month_win_percentage_{i}'] = month_win_percentage
    df_performance_by_month[f'month_point_percentage_{i}'] = month_point_percentage
    
df_performance_by_month

,team_code,team_name,end_season_rank,end_season_points,month_win_percentage_1,month_point_percentage_1,month_win_percentage_2,month_point_percentage_2,month_win_percentage_3,month_point_percentage_3,...,month_win_percentage_5,month_point_percentage_5,month_win_percentage_6,month_point_percentage_6,month_win_percentage_7,month_point_percentage_7,month_win_percentage_8,month_point_percentage_8,month_win_percentage_9,month_point_percentage_9
0,SOU,Southampton,15,43,0.500000,1.500000,0.666667,2.333333,0.333333,1.333333,...,0.200000,0.600000,0.000000,0.200000,0.500000,1.500000,0.000000,0.333333,0.40,1.20
1,MAN,Manchester United,2,74,0.333333,1.000000,0.333333,1.333333,1.000000,3.000000,...,0.571429,2.000000,0.200000,1.400000,1.000000,3.000000,0.666667,2.333333,0.40,1.40
2,BHA,Brighton & Hove Albion,16,41,0.250000,0.750000,0.000000,0.666667,0.333333,1.666667,...,0.500000,1.833333,0.000000,0.500000,0.500000,1.500000,0.250000,1.250000,0.25,1.00
3,WOL,Wolverhampton Wanderers,13,45,0.500000,1.500000,0.666667,2.333333,0.333333,1.333333,...,0.166667,0.833333,0.400000,1.600000,0.000000,0.333333,0.500000,1.750000,0.25,0.75
4,TOT,Tottenham Hotspur,7,62,0.500000,1.750000,0.666667,2.333333,0.666667,2.333333,...,0.400000,1.400000,0.400000,1.200000,0.600000,2.000000,0.500000,1.750000,0.50,1.50
5,AVL,Aston Villa,11,55,1.000000,3.000000,0.333333,1.000000,0.333333,1.000000,...,0.333333,1.000000,0.400000,1.400000,0.250000,1.250000,0.250000,1.000000,0.40,1.40
6,LEE,Leeds United,9,59,0.500000,1.750000,0.333333,1.000000,0.333333,1.333333,...,0.400000,1.200000,0.400000,1.200000,0.500000,1.750000,0.250000,1.250000,1.00,3.00
7,WHU,West Ham United,6,65,0.500000,1.500000,0.000000,0.666667,1.000000,3.000000,...,0.833333,2.500000,0.500000,1.750000,0.500000,1.750000,0.500000,1.500000,0.50,1.75
8,MNC,Manchester City,1,86,0.333333,1.333333,0.666667,2.333333,0.333333,1.333333,...,1.000000,3.000000,1.000000,3.000000,0.750000,2.250000,0.666667,2.000000,0.50,1.50
9,ARS,Arsenal,8,61,0.750000,2.250000,0.333333,1.000000,0.000000,0.333333,...,0.500000,1.833333,0.500000,1.500000,0.250000,1.250000,0.500000,1.750000,1.00,3.00
10,CRY,Crystal Palace,14,44,0.500000,1.500000,0.333333,1.333333,0.333333,1.000000,...,0.500000,1.666667,0.200000,1.000000,0.333333,1.333333,0.000000,0.000000,0.40,1.20
11,WBA,West Bromwich Albion,19,26,0.000000,0.250000,0.000000,0.666667,0.333333,1.000000,...,0.166667,0.666667,0.250000,1.250000,0.250000,1.000000,0.250000,1.250000,0.00,0.00
12,FUL,Fulham,18,28,0.000000,0.000000,0.333333,1.333333,0.333333,1.000000,...,0.000000,0.500000,0.400000,1.800000,0.200000,0.600000,0.000000,0.333333,0.00,0.25
13,SHEF,Sheffield United,20,23,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,...,0.500000,1.500000,0.200000,0.600000,0.000000,0.000000,0.250000,0.750000,0.50,1.50
14,LIV,Liverpool,3,69,0.750000,2.250000,0.666667,2.333333,0.333333,1.666667,...,0.333333,1.166667,0.250000,0.750000,0.500000,1.500000,0.333333,1.666667,1.00,3.00
15,NEW,Newcastle United,12,45,0.500000,1.750000,0.333333,1.333333,0.333333,1.000000,...,0.142857,0.428571,0.250000,1.000000,0.000000,0.750000,0.500000,1.750000,0.75,2.25
16,EVE,Everton,10,59,1.000000,3.000000,0.000000,0.333333,0.333333,1.000000,...,0.400000,1.400000,0.400000,1.400000,0.250000,1.000000,0.250000,1.250000,0.40,1.40
17,BRN,Burnley,17,39,0.000000,0.000000,0.000000,0.333333,0.333333,1.333333,...,0.333333,1.000000,0.166667,1.166667,0.333333,1.333333,0.250000,0.750000,0.25,0.75
18,CHE,Chelsea,4,67,0.500000,1.750000,0.333333,1.666667,0.666667,2.333333,...,0.400000,1.400000,0.600000,2.200000,0.500000,1.750000,0.750000,2.500000,0.50,1.50
19,LEI,Leicester City,5,66,0.750000,2.250000,0.666667,2.000000,0.333333,1.000000,...,0.666667,2.166667,0.400000,1.600000,0.666667,2.000000,0.500000,1.750000,0.25,0.75

In [6]:
df_performance_by_month.to_csv('../data/premier/premier_performance_by_month.csv',index = False)

In [12]:
df_month = pd.DataFrame()
months = [1,2,3,4,5,6,7,8,9]
df_month['month'] = months
month_index = [0,4,7,10,14,19,23,27,31,35]
for team in range(20):
    month_win_percentage = []
    month_point_percentage = []
    SPI_changes = []
    team_name = df['team_code'][team]
    for i in range(1,len(month_index)):
        actual_index = 35-month_index[i]
        last_index = 35-month_index[i-1]
        this_month = data[actual_index]["teams"][team]
        last_month = data[last_index]["teams"][team]
        game = this_month['current_wins']-last_month['current_wins']+this_month['current_ties']-last_month['current_ties']+this_month['current_losses']-last_month['current_losses']
        win_percentage = (this_month['current_wins']-last_month['current_wins'])/game
        point_percentage = (this_month['current_points']-last_month['current_points'])/game
        SPI_change = (this_month['global_rating']-last_month['global_rating'])
        month_win_percentage.append(win_percentage)
        month_point_percentage.append(point_percentage)
        SPI_changes.append(SPI_change)
    df_month[f'month_win_percentage_{team_name}'] = month_win_percentage
    df_month[f'month_point_percentage_{team_name}'] = month_point_percentage
    df_month[f'SPI_change_{team_name}'] = SPI_changes
df_month.to_csv('../data/premier/premier_month.csv',index = False)

In [26]:
df_week = pd.DataFrame()
weeks = np.arange(1,36,1)
df_week['week'] = weeks
for team in range(20):
    week_win_percentage = []
    week_point_percentage = []
    SPI_changes = []
    team_name = df['team_code'][team]
    for i in range(1,len(weeks)+1):
        actual_index = 35-i
        last_index = actual_index+1
        this_week = data[actual_index]["teams"][team]
        last_week = data[last_index]["teams"][team]
        game = this_week['current_wins']-last_week['current_wins']+this_week['current_ties']-last_week['current_ties']+this_week['current_losses']-last_week['current_losses']
        if game==0:
            win_percentage = None
            point_percentage = None
        else:
            win_percentage = (this_week['current_wins']-last_week['current_wins'])/game
            point_percentage = (this_week['current_points']-last_week['current_points'])/game
        SPI_change = (this_week['global_rating']-last_week['global_rating'])
        week_win_percentage.append(win_percentage)
        week_point_percentage.append(point_percentage)
        SPI_changes.append(SPI_change)
    df_week[f'week_win_percentage_{team_name}'] = week_win_percentage
    df_week[f'week_point_percentage_{team_name}'] = week_point_percentage
    df_week[f'SPI_change_{team_name}'] = SPI_changes
df_week.to_csv('../data/premier/premier_week.csv',index = False)

In [24]:
df_week_1 = pd.read_csv("../data/premier/premier_week.csv")

In [25]:
df_week_1

,week,week_win_percentage_SOU,week_point_percentage_SOU,SPI_change_SOU,week_win_percentage_MAN,week_point_percentage_MAN,SPI_change_MAN,week_win_percentage_BHA,week_point_percentage_BHA,SPI_change_BHA,...,SPI_change_EVE,week_win_percentage_BRN,week_point_percentage_BRN,SPI_change_BRN,week_win_percentage_CHE,week_point_percentage_CHE,SPI_change_CHE,week_win_percentage_LEI,week_point_percentage_LEI,SPI_change_LEI
0,1,0.0,3.0,-0.16308,NaN,NaN,0.00000,0.0,3.0,0.43121,...,0.91177,NaN,NaN,0.00000,1.0,3.0,-0.33601,1.0,3.0,1.32061
1,2,0.0,3.0,-1.37238,0.0,3.0,-1.45203,1.0,3.0,1.80500,...,0.84327,0.0,3.0,0.13881,0.0,3.0,-0.87541,1.0,3.0,-0.75189
2,3,1.0,3.0,0.71303,1.0,3.0,-1.41625,0.0,3.0,1.18379,...,0.80331,0.0,3.0,-0.17316,0.0,3.0,-0.51027,1.0,3.0,2.11517
3,4,1.0,3.0,0.65553,0.0,3.0,-2.62089,0.0,3.0,-1.06444,...,0.28651,0.0,3.0,-1.29917,1.0,3.0,0.86666,0.0,3.0,-1.87606
4,5,0.0,3.0,0.67623,1.0,3.0,1.34964,0.0,3.0,1.15012,...,-0.12269,0.0,3.0,0.43353,0.0,3.0,-0.97195,0.0,3.0,-1.09781
5,6,1.0,3.0,1.17463,0.0,3.0,1.71371,0.0,3.0,-0.51955,...,-0.78077,0.0,3.0,0.16560,0.0,3.0,0.74234,1.0,3.0,0.36512
6,7,1.0,3.0,-0.74157,0.0,3.0,-1.21896,0.0,3.0,0.03010,...,-0.75028,0.0,3.0,-1.05529,1.0,3.0,1.31020,1.0,3.0,0.82154
7,8,1.0,3.0,0.68211,1.0,3.0,0.61077,0.0,3.0,0.77302,...,-0.71506,0.0,3.0,-0.44518,1.0,3.0,0.46772,1.0,3.0,0.93429
8,9,0.0,3.0,0.11602,1.0,3.0,0.20068,1.0,3.0,0.26714,...,-0.49470,1.0,3.0,-0.10277,1.0,3.0,0.37628,0.0,3.0,-1.04006
9,10,0.0,3.0,-1.22318,1.0,3.0,0.20511,0.0,3.0,1.51529,...,-1.51660,0.0,3.0,-0.77513,0.0,3.0,1.11245,0.0,3.0,-1.97955
10,11,1.0,3.0,0.28054,1.0,3.0,-0.01950,0.0,3.0,-0.40517,...,0.50296,0.0,3.0,-0.45408,1.0,3.0,-0.12392,1.0,3.0,-0.38766
11,12,0.5,1.5,2.31720,0.0,3.0,-0.00631,0.0,1.5,-0.83144,...,2.09599,1.0,3.0,0.39496,0.0,1.5,-0.46556,0.5,1.5,-0.01096
12,13,0.0,3.0,0.29191,1.0,1.5,-0.27133,0.0,3.0,0.75193,...,-0.21187,0.5,1.5,0.27860,1.0,3.0,0.38023,1.0,3.0,1.08828
13,14,0.0,1.5,-0.62222,0.5,1.5,0.60229,0.0,1.5,-0.10945,...,0.29823,0.5,1.5,1.27662,0.0,1.5,-0.55081,0.0,1.5,0.33270
14,15,1.0,3.0,-0.52999,1.0,3.0,0.00770,0.0,3.0,0.16725,...,-0.65912,NaN,NaN,0.00000,0.0,3.0,-1.00932,1.0,3.0,0.23757
15,16,NaN,NaN,0.00000,1.0,3.0,0.59609,0.0,3.0,-0.37043,...,0.24353,0.0,3.0,-0.49065,NaN,NaN,0.00000,NaN,NaN,0.00000
16,17,0.0,3.0,-0.82815,0.5,1.5,-0.04361,1.0,3.0,1.05311,...,0.00000,0.0,3.0,-0.11089,0.5,1.5,-0.11727,1.0,1.5,1.77644
17,18,0.0,3.0,-0.80505,0.0,3.0,-0.86480,0.0,3.0,0.83166,...,-0.03846,1.0,1.5,0.30982,0.0,3.0,-0.09195,0.0,3.0,0.30218
18,19,0.0,1.5,-3.09805,0.5,1.5,3.11042,1.0,1.5,2.50008,...,-1.97740,0.0,1.5,-0.83474,1.0,3.0,0.40571,0.5,1.5,-1.02635
19,20,0.0,3.0,-0.10521,0.0,3.0,-0.79501,0.0,3.0,-1.68239,...,0.78282,0.0,3.0,1.60278,1.0,1.5,0.82825,0.0,3.0,-0.17797
20,21,0.0,3.0,-0.53819,0.0,3.0,-0.76282,0.0,3.0,1.46842,...,-2.18092,0.5,1.5,1.34923,1.0,3.0,0.20623,1.0,3.0,0.40567
21,22,0.0,1.5,-0.77781,1.0,3.0,1.31038,0.0,3.0,0.32487,...,1.24987,0.0,3.0,-0.73771,0.0,3.0,0.80377,1.0,3.0,-0.50090
22,23,0.0,3.0,-0.18367,0.0,1.5,-0.18132,0.0,3.0,-0.01276,...,0.62244,0.0,1.5,-1.13088,0.0,3.0,0.24587,0.0,1.5,-3.48679
23,24,0.5,1.5,1.84208,1.0,3.0,0.94891,0.0,3.0,-0.63085,...,-0.98241,0.0,3.0,-0.21917,1.0,1.5,1.10031,1.0,3.0,0.55756
24,25,0.0,3.0,-0.14387,1.0,3.0,-0.06126,1.0,3.0,0.27764,...,-0.73331,1.0,3.0,0.37094,0.0,3.0,0.18759,1.0,3.0,2.34384
25,26,NaN,NaN,0.00000,NaN,NaN,0.05972,1.0,3.0,1.03036,...,0.00000,NaN,NaN,0.00000,NaN,NaN,0.00000,NaN,NaN,0.00000
26,27,1.0,3.0,0.15834,1.0,3.0,-0.12878,0.0,3.0,0.05157,...,0.09726,0.0,3.0,-1.03463,0.0,3.0,-1.92617,0.0,3.0,-0.78113
27,28,0.0,3.0,-2.36904,1.0,3.0,0.78258,0.0,3.0,0.27515,...,0.11171,0.0,3.0,-0.47606,1.0,3.0,-0.09448,0.0,3.0,0.24774
28,29,0.0,3.0,0.11212,1.0,3.0,-0.35464,0.0,3.0,0.80833,...,0.79485,0.0,3.0,-0.28251,0.0,3.0,-0.23234,NaN,NaN,0.00000
29,30,NaN,NaN,0.00000,0.0,3.0,0.59334,0.0,3.0,-0.06473,...,0.92182,1.0,3.0,3.22170,1.0,3.0,1.31749,1.0,1.5,0.87288
30,31,0.0,3.0,-1.01222,NaN,NaN,0.35643,1.0,3.0,1.09466,...,-0.83494,0.0,3.0,-0.86607,1.0,3.0,0.99389,0.0,3.0,0.84818
31,32,0.5,1.5,-0.17624,0.5,1.5,-1.88344,0.0,3.0,-1.02921,...,0.84459,1.0,3.0,0.96036,0.5,1.5,0.49779,0.5,1.5,-0.57276
32,33,0.5,1.5,0.26585,0.0,1.5,-1.50851,0.5,1.5,0.56489,...,-0.13821,0.0,1.5,-2.23199,1.0,3.0,0.01139,0.0,3.0,-0.20576
33,34,0.0,3.0,-0.06504,1.0,3.0,-0.16104,0.0,3.0,-0.95039,...,-1.04189,0.0,3.0,-0.07127,0.0,3.0,0.07759,0.0,3.0,-1.47421
34,35,NaN,NaN,0.00000,NaN,NaN,0.00000,NaN,NaN,0.00000,...,0.00000,NaN,NaN,0.00000,NaN,NaN,0.53209,NaN,NaN,0.00000