In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
from datetime import datetime,timedelta
import tqdm.notebook as tq

In [3]:
df_p1s1 = pd.read_csv('../data/comments/player/sentiment/Sterling_MNC_sentiment.csv')
df_p1s2 = pd.read_csv('../data/comments/player/sentiment/Sterling_national_team_sentiment.csv')
df_p1s3 = pd.read_csv('../data/comments/player/sentiment/Sterling_premier_sentiment.csv')
df_p1s4 = pd.read_csv('../data/comments/player/sentiment/Sterling_soccer_sentiment.csv')
df_p1s5 = pd.read_csv('../data/comments/player/sentiment/Sterling_football_sentiment.csv')

/Users/feegee2000/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [12]:
df_p1s4_neg = df_p1s4.loc[df_p1s4.sentiment_score<-0.05]

df_as = df_p1s4.groupby(['author'], as_index = False)['sentiment_score'].count()
df_as.rename(columns={'sentiment_score':'count'},inplace=True)

df_as = df_as.loc[df_as['count']>10]

df_as_neg = df_p1s4_neg.groupby(['author'])['sentiment_score'].count()

neg = []
for i in tq.tqdm(range(df_as.shape[0])):
    if df_as.iloc[i]['author'] in df_as_neg.index:
        neg.append(df_as_neg[df_as.iloc[i]['author']])
    else:
        neg.append(0)

df_as['neg_count'] = neg
df_as['neg_rate'] = df_as['neg_count']/df_as['count']

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=2088.0), HTML(value='')))

In [13]:
neg_author_p1s4 = df_as.sort_values(by='neg_rate',ascending=False)[:50]

In [14]:
df_p1s1_neg = df_p1s1.loc[df_p1s1.sentiment_score<-0.05]

df_as = df_p1s1.groupby(['author'], as_index = False)['sentiment_score'].count()
df_as.rename(columns={'sentiment_score':'count'},inplace=True)

df_as = df_as.loc[df_as['count']>10]

df_as_neg = df_p1s1_neg.groupby(['author'])['sentiment_score'].count()

neg = []
for i in tq.tqdm(range(df_as.shape[0])):
    if df_as.iloc[i]['author'] in df_as_neg.index:
        neg.append(df_as_neg[df_as.iloc[i]['author']])
    else:
        neg.append(0)

df_as['neg_count'] = neg
df_as['neg_rate'] = df_as['neg_count']/df_as['count']

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=561.0), HTML(value='')))

In [15]:
neg_author_p1s1 = df_as.sort_values(by='neg_rate',ascending=False)[:50]

In [18]:
authors = set(neg_author_p1s1.author).intersection((neg_author_p1s4.author))

In [16]:
neg_author_p1s4

                     author  count  neg_count  neg_rate
23340           deathbladev     13         11  0.846154
17091            TSUUUUUUUU     18         15  0.833333
18835        Vapourtrails89     11          9  0.818182
3697         Colonel_Getafe     26         21  0.807692
17778   TheScarletPimpernel     19         15  0.789474
6715         GerrardSlip666     13         10  0.769231
8601               JaM0k3_1     13         10  0.769231
27082                 jstuu     17         13  0.764706
4861         DoTheEvolution     12          9  0.750000
5035              Dr_Oetker     16         12  0.750000
1041          AleDelPiero10     16         12  0.750000
23510         dickbutts3000     19         14  0.736842
5181         DunneAndDusted     19         14  0.736842
26726              jdbolick     26         19  0.730769
30908   putcoolusernamehere     11          8  0.727273
28957               midas22     17         12  0.705882
30794              pretwicz     13          9  0.692308
176                 123Many     16         11  0.687500
22528                chokyx     28         19  0.678571
14020            PureExcuse     15         10  0.666667
22371               cfctony     15         10  0.666667
14389     RavenhillsRedHand     15         10  0.666667
17108               Table53     15         10  0.666667
22515        chirstopher0us     15         10  0.666667
11844            Mountain55     27         18  0.666667
28663            matbezlima     17         11  0.647059
475              6footkilla     14          9  0.642857
5939            FearFailure     14          9  0.642857
11783            Moosterton     11          7  0.636364
17517       TheEnglish_King     11          7  0.636364
2201   BestFriendWatermelon     11          7  0.636364
8047         IcryforBallard     11          7  0.636364
4046                CuleAss     11          7  0.636364
7830                IAIRonI     11          7  0.636364
15601         SeparatePrice     16         10  0.625000
11814              Morsrael     13          8  0.615385
9561               Keskekun     26         16  0.615385
3812               Coolica1     13          8  0.615385
20453          agueroisgoat     13          8  0.615385
1618     AtheistCreationist     43         26  0.604651
17657      TheMexicanAvatar     15          9  0.600000
32452  smackonmytidybooster     17         10  0.588235
21251           bakugou-kun     17         10  0.588235
5070             DreadWolf3     17         10  0.588235
24262            escherbach     17         10  0.588235
23541       dillonfinchbeck     12          7  0.583333
35595             zzackfair     12          7  0.583333
3499        ChristianMunich     12          7  0.583333
9770            Koinfamous2     12          7  0.583333
8921            JesseLingod     12          7  0.583333

In [17]:
neg_author_p1s1

                    author  count  neg_count  neg_rate
814            Fernandingo     11          9  0.818182
3165                damp_s     12          8  0.666667
1955          Ravensfan967     12          8  0.666667
686       DreamerScreamers     11          7  0.636364
3704          jellyravel23     13          8  0.615385
1767       Oldmanfirebobby     13          8  0.615385
2051            Sawyer86uk     13          8  0.615385
4493              seanpwns     13          8  0.615385
1488  ManufacturerDeep2800     23         14  0.608696
3159          daboswanimoi     30         18  0.600000
1669            NathanMo18     15          9  0.600000
4636          suckamadicka     15          9  0.600000
95               A_chilles     17         10  0.588235
4710     thedeatheater1410     17         10  0.588235
4119                 mxxxz     14          8  0.571429
4097         mr_poppington     35         20  0.571429
2241          Striderite23     14          8  0.571429
3143              ctid1987     11          6  0.545455
3747              joveticc     11          6  0.545455
3459                gggd68     13          7  0.538462
1622       Mr_CheeseGrater     13          7  0.538462
2192      SorrowsNativeSon     13          7  0.538462
4272             pgisiddiq     13          7  0.538462
427               Captluck     15          8  0.533333
3122       cornerstorecult     17          9  0.529412
1771              OliveBoi     17          9  0.529412
3785      karatechopmaster     17          9  0.529412
2601               Xbot_69     31         16  0.516129
4014            maxime0299     94         48  0.510638
2358  TheIncompetenceOfMan     20         10  0.500000
2476       TrueBlueCitizen     12          6  0.500000
2059       SchottyTheHotty     20         10  0.500000
1022              Holymani     18          9  0.500000
2053          Sayanroman94     16          8  0.500000
2991            bulletsssz     30         15  0.500000
898               G_Thirty     18          9  0.500000
146                Aletico     12          6  0.500000
1805              Oyabinol     12          6  0.500000
4888        whodatnation70     37         18  0.486486
749            Elemental05     74         35  0.472973
3069            chocomilkz     17          8  0.470588
376           Brfootball47     17          8  0.470588
1202        JerobifromATCQ     17          8  0.470588
3474              globe187     15          7  0.466667
3260            dracob2099     15          7  0.466667
1838     Patrickk_batemann     28         13  0.464286
4895         wigglerwiggle     13          6  0.461538
484            Citizen_Kun     13          6  0.461538
4602         spooki_boogey     13          6  0.461538
1906              QuackeN_     13          6  0.461538

In [24]:
authors = list(set(neg_author_p1s4.author).union(set(neg_author_p1s1.author)))

In [26]:
authors = pd.concat([neg_author_p1s4,neg_author_p1s1])

In [27]:
authors

                    author  count  neg_count  neg_rate
23340          deathbladev     13         11  0.846154
17091           TSUUUUUUUU     18         15  0.833333
18835       Vapourtrails89     11          9  0.818182
3697        Colonel_Getafe     26         21  0.807692
17778  TheScarletPimpernel     19         15  0.789474
...                    ...    ...        ...       ...
1838     Patrickk_batemann     28         13  0.464286
4895         wigglerwiggle     13          6  0.461538
484            Citizen_Kun     13          6  0.461538
4602         spooki_boogey     13          6  0.461538
1906              QuackeN_     13          6  0.461538

[100 rows x 4 columns]

In [28]:
authors.to_csv('../data/author/Sterling_negative_author.csv',index=False)

In [29]:
group1 = pd.read_csv('../data/comments/author_bg/sentiment/player_group1_comments.csv')

In [55]:
print("negative sentiment comments proportion:")
print(group1.loc[group1.sentiment_score<-0.05].groupby(['player'])['sentiment_score'].count()/group1.groupby(['player'])['sentiment_score'].count())

negative sentiment comments proportion:
player
Bruyne      0.276923
Kane        0.313475
Lingard     0.277955
Mahrez      0.355254
Rashford    0.361803
Sterling    0.463473
Stones      0.322050
Name: sentiment_score, dtype: float64

In [42]:
ss = group1.groupby(['author','player'],as_index=False)['sentiment_score'].mean()

In [40]:
ats = authors.author.unique()
columns = ['Sterling','Bruyne','Stones','Mahrez', 'Kane', 'Rashford', 'Lingard']
df = pd.DataFrame(columns=columns,index=ats)

In [44]:
for i in range(ss.shape[0]):
    df.loc[ss.iloc[i]['author']][ss.iloc[i]['player']] = ss.iloc[i]['sentiment_score']

In [51]:
df['Bruyne_Sterling'] = abs(df['Bruyne']-df['Sterling'])
df['Stones_Sterling'] = abs(df['Stones']-df['Sterling'])
df['Mahrez_Sterling'] = abs(df['Mahrez']-df['Sterling'])
df['Kane_Sterling'] = abs(df['Kane']-df['Sterling'])
df['Rashford_Sterling'] = abs(df['Rashford']-df['Sterling'])
df['Lingard_Sterling'] = abs(df['Lingard']-df['Sterling'])

In [53]:
df.loc[df.Sterling<-0.05].mean()

Sterling            -0.187244
Bruyne               0.135111
Stones               0.166183
Mahrez               0.025052
Kane                 0.106576
Rashford             0.122327
Lingard              0.236644
Bruyne_Sterling      0.422798
Stones_Sterling      0.394234
Mahrez_Sterling      0.280501
Kane_Sterling        0.313784
Rashford_Sterling    0.349790
Lingard_Sterling     0.479533
dtype: float64